# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-29 16:27
from __future__ import unicode_literals

import dj4xol.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('django_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='dj4xol_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=60)),
                ('alias', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('map_size_x', models.IntegerField()),
                ('map_size_y', models.IntegerField()),
                ('joinable', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('ended', models.BooleanField(default=False)),
                ('year', models.IntegerField(default=2400)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_games', to='dj4xol.Account')),
            ],
        ),
        migrations.CreateModel(
            name='GameMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('year', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamemessages', to='dj4xol.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('plural_name', models.CharField(default=None, max_length=16, null=True)),
                ('formal_name', models.CharField(default=None, max_length=32, null=True)),
                ('description', models.TextField(default=None, null=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='dj4xol.Account')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='dj4xol.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('plural_name', models.CharField(max_length=16)),
                ('formal_name', models.CharField(max_length=32)),
                ('public', models.BooleanField(default=False)),
                ('description', models.TextField(default=None, null=True)),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_races', to='dj4xol.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ServerRaceType',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('starting_population', models.IntegerField(default=1000)),
                ('starting_planets', models.IntegerField(default=1)),
                ('starting_planet_has_stargate', models.BooleanField(default=False)),
                ('starting_planet_has_massdriver', models.BooleanField(default=False)),
                ('population_growth_multiplier', models.FloatField(default=1.0)),
                ('population_growth_uses_resources', models.BooleanField(default=False)),
                ('starting_economy', models.IntegerField(default=2)),
                ('economy_offset', models.IntegerField(default=0)),
                ('manufacturing_multiplier', models.FloatField(default=1.0)),
                ('combat_multiplier', models.FloatField(default=1.0)),
                ('defence_multiplier', models.FloatField(default=1.0)),
                ('bombardment_multiplier', models.FloatField(default=1.0)),
                ('ground_force_multiplier', models.FloatField(default=1.0)),
                ('diplomacy_multiplier', models.FloatField(default=1.0)),
                ('trade_multiplier', models.FloatField(default=1.0)),
                ('scan_multiplier', models.FloatField(default=1.0)),
                ('shield_multiplier', models.FloatField(default=1.0)),
                ('warp_multiplier', models.FloatField(default=1.0)),
                ('stealth_multiplier', models.FloatField(default=1.0)),
                ('terraforming_multiplier', models.FloatField(default=1.0)),
                ('metalurgy_multiplier', models.FloatField(default=1.0)),
                ('political_stability', models.FloatField(default=1.0)),
                ('luck_multiplier', models.FloatField(default=1.0)),
                ('persuasion_multiplier', models.FloatField(default=1.0)),
                ('chance_of_scantheft', models.FloatField(default=0.01)),
                ('ignores_radiation', models.BooleanField(default=False)),
                ('ignores_temperature', models.BooleanField(default=False)),
                ('ignores_gravity', models.BooleanField(default=False)),
                ('requires_space_station', models.BooleanField(default=False)),
                ('has_terraforming', models.BooleanField(default=True)),
                ('has_advanced_mines', models.BooleanField(default=False)),
                ('has_advanced_stargates', models.BooleanField(default=False)),
                ('has_advanced_remoteminers', models.BooleanField(default=False)),
                ('has_advanced_hulls', models.BooleanField(default=False)),
                ('has_superweapon', models.BooleanField(default=False)),
                ('has_bombs', models.BooleanField(default=True)),
                ('has_metalurgy', models.BooleanField(default=True)),
                ('has_stealth', models.BooleanField(default=True)),
                ('has_generalised_research', models.BooleanField(default=False)),
                ('is_parasitic', models.BooleanField(default=False)),
                ('is_cybernetic', models.BooleanField(default=False)),
                ('is_mechanical', models.BooleanField(default=False)),
                ('is_energy_being', models.BooleanField(default=False)),
                ('starting_research_points', models.IntegerField(default=3)),
                ('research_multiplier', models.FloatField(default=1.0)),
                ('initiative_multiplier', models.FloatField(default=1.0)),
                ('cargo_multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Server Setting',
                'verbose_name_plural': 'Server Settings',
            },
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='dj4xol.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='dj4xol.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShipOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.BooleanField(default=False)),
                ('warpfactor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(13)])),
                ('x', models.IntegerField(null=True)),
                ('y', models.IntegerField(null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shiporderss', to='dj4xol.Game')),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dj4xol.Ship')),
                ('target_ship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dj4xol.Ship')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('gravity', models.FloatField(default=dj4xol.models.random_environmental_init, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('temperature', models.FloatField(default=dj4xol.models.random_environmental_init, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('radiation', models.FloatField(default=dj4xol.models.random_environmental_init, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)])),
                ('gravity_adjustment', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('temperature_adjustment', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('radiation_adjustment', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('ironium', models.IntegerField(default=dj4xol.models.random_resource_init, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('boranium', models.IntegerField(default=dj4xol.models.random_resource_init, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('germanium', models.IntegerField(default=dj4xol.models.random_resource_init, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('colonists', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='dj4xol.Game')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stars', to='dj4xol.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shiporders',
            name='target_star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dj4xol.Star'),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='race_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj4xol.ServerRaceType'),
        ),
        migrations.AddField(
            model_name='player',
            name='homeworld',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworld_of', to='dj4xol.Star'),
        ),
        migrations.AddField(
            model_name='player',
            name='race_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj4xol.ServerRaceType'),
        ),
        migrations.AddField(
            model_name='gamemessage',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dj4xol.Player'),
        ),
    ]
