# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-29 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='join_until_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
