# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-07 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
