# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-31 22:58
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=dj4xol.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('order_type', models.CharField(choices=[('TERRAFORM_GRAVITY', 'Terraform Gravity'), ('TERRAFORM_TEMPERATURE', 'Terraform Temperature'), ('TERRAFORM_RADIATION', 'Terraform Radiation')], max_length=24)),
                ('position', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productionorders', to='dj4xol.Game')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='dj4xol.Star')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
