# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0002_auto_20260129_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_invitations', to='dj4xol.Account')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='dj4xol.Game')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gameinvitation',
            unique_together=set([('game', 'account'), ('game', 'email')]),
        ),
    ]
