# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-31 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0002_add_production_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productionorder',
            unique_together=set([('star', 'order_type')]),
        ),
    ]
