# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-07 12:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dj4xol', '0002_game_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSettings',
            fields=[
                ('key', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=60)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
