# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-07 13:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0003_serversettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serversettings',
            options={'verbose_name': 'Server Setting', 'verbose_name_plural': 'Server Settings'},
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
