# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0003_game_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='turn_scheme',
            field=models.CharField(choices=[('QUORUM', 'Quorum - when all players are ready'), ('OWNER', 'Owner - when game owner triggers'), ('HOURLY', 'Hourly'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly')], default='QUORUM', max_length=10),
        ),
    ]
