# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-31 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0003_production_order_unique_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='gravity_adjustment',
        ),
        migrations.RemoveField(
            model_name='star',
            name='radiation_adjustment',
        ),
        migrations.RemoveField(
            model_name='star',
            name='temperature_adjustment',
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_type',
            field=models.CharField(choices=[('TERRAFORM_GRAVITY', 'Terraform Gravity (1%)'), ('TERRAFORM_TEMPERATURE', 'Terraform Temperature (1%)'), ('TERRAFORM_RADIATION', 'Terraform Radiation (1%)')], max_length=24),
        ),
    ]
