# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0004_turn_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='next_generation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
