# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-07 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0004_auto_20230707_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('plural_name', models.CharField(max_length=16)),
                ('public', models.BooleanField(default=False)),
                ('description', models.TextField(default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playerraces', to='dj4xol.Game')),
                ('owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_races', to='dj4xol.Player')),
                ('player', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='dj4xol.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRaceType',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('starting_population', models.IntegerField(default=1000)),
                ('starting_planets', models.IntegerField(default=1)),
                ('starting_planet_has_stargate', models.BooleanField(default=False)),
                ('starting_planet_has_massdriver', models.BooleanField(default=False)),
                ('population_growth_multiplier', models.FloatField(default=1.0)),
                ('population_growth_uses_resources', models.BooleanField(default=False)),
                ('starting_economy', models.IntegerField(default=2)),
                ('economy_offset', models.IntegerField(default=0)),
                ('manufacturing_multiplier', models.FloatField(default=1.0)),
                ('combat_multiplier', models.FloatField(default=1.0)),
                ('defence_multiplier', models.FloatField(default=1.0)),
                ('bombardment_multiplier', models.FloatField(default=1.0)),
                ('ground_force_multiplier', models.FloatField(default=1.0)),
                ('diplomacy_multiplier', models.FloatField(default=1.0)),
                ('trade_multiplier', models.FloatField(default=1.0)),
                ('scan_multiplier', models.FloatField(default=1.0)),
                ('shield_multiplier', models.FloatField(default=1.0)),
                ('warp_multiplier', models.FloatField(default=1.0)),
                ('stealth_multiplier', models.FloatField(default=1.0)),
                ('terraforming_multiplier', models.FloatField(default=1.0)),
                ('metalurgy_multiplier', models.FloatField(default=1.0)),
                ('political_stability', models.FloatField(default=1.0)),
                ('luck_multiplier', models.FloatField(default=1.0)),
                ('persuasion_multiplier', models.FloatField(default=1.0)),
                ('chance_of_scantheft', models.FloatField(default=0.01)),
                ('ignores_radiation', models.BooleanField(default=False)),
                ('ignores_temperature', models.BooleanField(default=False)),
                ('ignores_gravity', models.BooleanField(default=False)),
                ('requires_space_station', models.BooleanField(default=False)),
                ('has_terraforming', models.BooleanField(default=True)),
                ('has_advanced_mines', models.BooleanField(default=False)),
                ('has_advanced_stargates', models.BooleanField(default=False)),
                ('has_advanced_remoteminers', models.BooleanField(default=False)),
                ('has_advanced_hulls', models.BooleanField(default=False)),
                ('has_superweapon', models.BooleanField(default=False)),
                ('has_bombs', models.BooleanField(default=True)),
                ('has_metalurgy', models.BooleanField(default=True)),
                ('has_stealth', models.BooleanField(default=True)),
                ('is_parasitic', models.BooleanField(default=False)),
                ('is_cybernetic', models.BooleanField(default=False)),
                ('is_mechanical', models.BooleanField(default=False)),
                ('is_energy_being', models.BooleanField(default=False)),
                ('starting_research_points', models.IntegerField(default=3)),
                ('research_multiplier', models.FloatField(default=1.0)),
                ('initiative_multiplier', models.FloatField(default=1.0)),
                ('cargo_multiplier', models.FloatField(default=1.0)),
            ],
        ),
        migrations.AddField(
            model_name='playerrace',
            name='race_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dj4xol.ServerRaceType'),
        ),
    ]
