# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-31 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0004_remove_adjustment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='random_events',
            field=models.BooleanField(default=False),
        ),
    ]
