# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0005_add_random_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_seen_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
