# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0005_turn_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='years_per_turn',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='turned_in',
            field=models.BooleanField(default=False),
        ),
    ]
