# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-07 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0005_auto_20230707_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverracetype',
            name='id',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
