# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-07 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0006_auto_20230707_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverracetype',
            old_name='id',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='serversettings',
            name='key',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
