# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0006_quorum_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='serverrace',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
