# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-10 21:53
from __future__ import unicode_literals

import dj4xol.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0007_auto_20230707_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverracetype',
            name='has_generalised_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='star',
            name='boranium',
            field=models.IntegerField(default=dj4xol.models.random_resource_init, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='star',
            name='colonists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='germanium',
            field=models.IntegerField(default=dj4xol.models.random_resource_init, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='star',
            name='gravity',
            field=models.FloatField(default=dj4xol.models.random_environmental_init, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='star',
            name='gravity_adjustment',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='star',
            name='ironium',
            field=models.IntegerField(default=dj4xol.models.random_resource_init, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='star',
            name='radiation',
            field=models.FloatField(default=dj4xol.models.random_environmental_init, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='star',
            name='radiation_adjustment',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='star',
            name='temperature',
            field=models.FloatField(default=dj4xol.models.random_environmental_init, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(2.0)]),
        ),
        migrations.AddField(
            model_name='star',
            name='temperature_adjustment',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
