# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0007_optional_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gravity_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='gravity_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='radiation_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='radiation_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='temperature_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='temperature_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='gravity_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='gravity_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='radiation_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='radiation_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='temperature_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='temperature_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverracetype',
            name='gravity_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverracetype',
            name='gravity_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverracetype',
            name='radiation_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverracetype',
            name='radiation_width',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverracetype',
            name='temperature_center',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='serverracetype',
            name='temperature_width',
            field=models.FloatField(default=1.0),
        ),
    ]
