# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-01 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0007_add_messages_seen_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemessage',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DIPLOMATIC', 'Diplomatic'), ('ENVIRONMENTAL', 'Environmental'), ('POPULATION', 'Population'), ('RANDOM', 'Random Event'), ('COMBAT', 'Combat'), ('PRODUCTION', 'Production')], default='GENERAL', max_length=16),
        ),
    ]
