# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0008_habitability_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='homeworld_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='homeworld_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
