# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-01 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0008_add_message_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_type',
            field=models.CharField(choices=[('TERRAFORM_GRAVITY', 'Terraform Gravity (1%)'), ('TERRAFORM_TEMPERATURE', 'Terraform Temperature (1%)'), ('TERRAFORM_RADIATION', 'Terraform Radiation (1%)'), ('BUILD_FLEET', 'Build Fleet')], max_length=24),
        ),
        migrations.AlterUniqueTogether(
            name='productionorder',
            unique_together=set([]),
        ),
    ]
