# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-07-10 21:55
from __future__ import unicode_literals

from django.db import migrations

def populate_resources(apps, schema_editor):
    """Populate the resources and environmentals of all stars with random values."""
    import random
    def random_resource_init():
        return random.randint(0,100)
    def random_environmental_init():
        return random.random() * 2.0
    
    Star = apps.get_model('dj4xol', 'Star')
    for star in Star.objects.all():
        star.boranium = random_resource_init()
        star.ironium = random_resource_init()
        star.germanium = random_resource_init()
        star.gravity = random_environmental_init()
        star.radiation = random_environmental_init()
        star.temperature = random_environmental_init()
        star.save()

class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0008_auto_20230710_2153'),
    ]

    operations = [
    ]
