# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 15:34
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0009_homeworld_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='base_capacity',
            field=models.IntegerField(default=dj4xol.models.random_capacity_init),
        ),
    ]
