# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-01 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0009_auto_20260201_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
    ]
