# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-02 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0010_add_is_generating_to_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='factories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='mines',
            field=models.IntegerField(default=0),
        ),
    ]
