# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-08-28 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0010_auto_20230724_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverrace',
            name='game',
        ),
        migrations.AddField(
            model_name='playerrace',
            name='homeworld',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworld_of', to='dj4xol.Star'),
        ),
    ]
