# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2025-08-28 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0011_auto_20250828_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mygames', to='dj4xol.Player'),
        ),
    ]
