# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-01-30 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0011_rename_ship_to_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='heading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='fleetorders',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleetorderss', to='dj4xol.Game'),
        ),
    ]
