# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0011_add_mines_and_factories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='order_type',
            field=models.CharField(choices=[('TERRAFORM_GRAVITY', 'Terraform Gravity (1%)'), ('TERRAFORM_TEMPERATURE', 'Terraform Temperature (1%)'), ('TERRAFORM_RADIATION', 'Terraform Radiation (1%)'), ('BUILD_FLEET', 'Build Fleet'), ('BUILD_MINE', 'Build Mine'), ('BUILD_FACTORY', 'Build Factory')], max_length=24),
        ),
    ]
