# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-02 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0012_auto_20260202_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='boranium_surface',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='germanium_surface',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='ironium_surface',
            field=models.IntegerField(default=0),
        ),
    ]
