# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-02 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0014_add_defenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='repeat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='star',
            name='buildpoints_consumed',
            field=models.IntegerField(default=0),
        ),
    ]
