# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-02 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0015_auto_20260202_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='progress',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='spent_boranium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='spent_bp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='spent_germanium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='spent_ironium',
            field=models.IntegerField(default=0),
        ),
    ]
