# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-02 20:29
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0017_remove_productionorder_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='colonists_busy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='star',
            name='boranium_surface',
            field=models.IntegerField(default=dj4xol.models.random_surface_mineral_init),
        ),
        migrations.AlterField(
            model_name='star',
            name='germanium_surface',
            field=models.IntegerField(default=dj4xol.models.random_surface_mineral_init),
        ),
        migrations.AlterField(
            model_name='star',
            name='ironium_surface',
            field=models.IntegerField(default=dj4xol.models.random_surface_mineral_init),
        ),
    ]
