# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-02 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0018_add_colonists_busy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='colonists_busy',
        ),
    ]
