# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-03 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0019_remove_colonists_busy'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='boranium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fleet',
            name='cargo_capacity',
            field=models.IntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='fleet',
            name='colonists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fleet',
            name='germanium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fleet',
            name='ironium',
            field=models.IntegerField(default=0),
        ),
    ]
