# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-03 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0020_add_fleet_cargo_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('TRANSFER', 'Transfer')], default='MOVE', max_length=10),
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='transfer_boranium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='transfer_colonists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='transfer_germanium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='transfer_ironium',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('LOAD', 'Load'), ('UNLOAD', 'Unload')], max_length=10, null=True),
        ),
    ]
