# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-03 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0021_add_fleet_transfer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='cargo_capacity',
            field=models.IntegerField(default=1000),
        ),
    ]
