# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-04 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0022_update_fleet_cargo_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleet',
            old_name='boranium',
            new_name='boranium_inventory',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='germanium',
            new_name='germanium_inventory',
        ),
        migrations.RenameField(
            model_name='fleet',
            old_name='ironium',
            new_name='ironium_inventory',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='boranium_surface',
            new_name='boranium_inventory',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='boranium',
            new_name='boranium_yield',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='germanium_surface',
            new_name='germanium_inventory',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='germanium',
            new_name='germanium_yield',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='ironium_surface',
            new_name='ironium_inventory',
        ),
        migrations.RenameField(
            model_name='star',
            old_name='ironium',
            new_name='ironium_yield',
        ),
    ]
