# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-06 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0023_rename_resource_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='dry_mass',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('COLONISE', 'Colonise')], default='MOVE', max_length=10),
        ),
    ]
