# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-06 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0024_auto_20260206_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemessage',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
