# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-06 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0025_add_message_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetorders',
            name='transfer_type',
            field=models.CharField(blank=True, choices=[('LOAD', 'Load'), ('UNLOAD', 'Unload'), ('UNLOAD_ALL', 'Unload All')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gamemessage',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General'), ('DIPLOMATIC', 'Diplomatic'), ('ENVIRONMENTAL', 'Environmental'), ('POPULATION', 'Population'), ('RANDOM', 'Random Event'), ('COMBAT', 'Combat'), ('PRODUCTION', 'Production'), ('EXCEPTION', 'Exception')], default='GENERAL', max_length=16),
        ),
    ]
