# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-06 22:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0026_auto_20260206_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='integrity',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='fleet',
            name='max_safe_warp',
            field=models.IntegerField(default=5),
        ),
    ]
