# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-08 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0027_auto_20260206_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='serversettings',
            name='long_value',
            field=models.TextField(blank=True, default=''),
        ),
    ]
