# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-08 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0028_add_long_value_to_serversettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('lcars', 'LCARS')], default='classic', max_length=20),
        ),
    ]
