# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-09 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0029_add_theme_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='ship_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='theme',
            field=models.CharField(choices=[('classic', 'Classic'), ('lcars', 'LCARS'), ('win95', 'Windows 95')], default='classic', max_length=20),
        ),
        migrations.AlterField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('COLONISE', 'Colonise'), ('MERGE', 'Merge')], default='MOVE', max_length=10),
        ),
    ]
