# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-09 16:06
from __future__ import unicode_literals

import dj4xol.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0030_auto_20260209_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salvage',
            fields=[
                ('id', models.UUIDField(default=dj4xol.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('ironium_inventory', models.IntegerField(default=0)),
                ('boranium_inventory', models.IntegerField(default=0)),
                ('germanium_inventory', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvages', to='dj4xol.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fleet',
            name='cargo_capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('TRANSFER', 'Transfer'), ('COLONISE', 'Colonise'), ('MERGE', 'Merge'), ('SCUTTLE', 'Scuttle')], default='MOVE', max_length=10),
        ),
        migrations.AlterField(
            model_name='star',
            name='boranium_yield',
            field=models.IntegerField(default=dj4xol.models.random_boranium_yield, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='star',
            name='germanium_yield',
            field=models.IntegerField(default=dj4xol.models.random_germanium_yield, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='star',
            name='ironium_yield',
            field=models.IntegerField(default=dj4xol.models.random_ironium_yield, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='target_salvage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dj4xol.Salvage'),
        ),
    ]
