# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-09 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0031_add_salvage_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='shipyards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_type',
            field=models.CharField(choices=[('TERRAFORM_GRAVITY', 'Terraform Gravity (1%)'), ('TERRAFORM_TEMPERATURE', 'Terraform Temperature (1%)'), ('TERRAFORM_RADIATION', 'Terraform Radiation (1%)'), ('BUILD_FLEET', 'Build Fleet'), ('BUILD_MINE', 'Build Mine'), ('BUILD_FACTORY', 'Build Factory'), ('BUILD_DEFENSE', 'Build Defense'), ('BUILD_SHIPYARD', 'Build Shipyard')], max_length=24),
        ),
    ]
