# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-09 18:35
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0032_add_shipyards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=dj4xol.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('year', models.IntegerField()),
                ('target_type', models.CharField(choices=[('star', 'Star'), ('fleet', 'Fleet'), ('salvage', 'Salvage')], max_length=10)),
                ('target_id', models.UUIDField()),
                ('cached_report', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dj4xol.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dj4xol.Player')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='report',
            unique_together=set([('player', 'target_type', 'target_id')]),
        ),
    ]
