# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-10 22:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0034_add_patrol_intercept_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('INTERCEPT', 'Intercept'), ('TRANSFER', 'Transfer'), ('COLONISE', 'Colonise'), ('MERGE', 'Merge'), ('SCUTTLE', 'Scuttle'), ('PATROL', 'Patrol')], default='MOVE', max_length=10),
        ),
    ]
