# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dj4xol', '0039_remove_formal_name_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrace',
            name='starting_colonists',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='player',
            name='starting_colonists',
            field=models.IntegerField(default=10),
        ),
    ]
