# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dj4xol', '0040_add_starting_colonists'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrace',
            name='starting_mines',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='starting_factories',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='starting_shipyards',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='starting_fleets',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='starting_mines',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='player',
            name='starting_factories',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='player',
            name='starting_shipyards',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='player',
            name='starting_fleets',
            field=models.IntegerField(default=2),
        ),
    ]
