# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dj4xol', '0041_add_starting_infrastructure'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverrace',
            name='leftover_points',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='leftover_points',
            field=models.FloatField(default=0.0),
        ),
    ]
