# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-23 13:29
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0042_add_leftover_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerResearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_level', models.FloatField(default=0.0)),
                ('stored_rp', models.FloatField(default=0.0)),
                ('allocation_percent', models.FloatField(default=25.0)),
            ],
            options={
                'ordering': ['category__display_order', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='ResearchCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Research categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=dj4xol.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('level', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, default='')),
                ('tech_type', models.CharField(choices=[('PROPULSION', 'Propulsion'), ('WEAPON', 'Weapon'), ('SHIELD', 'Shield'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('params_json', models.TextField(default='{}')),
                ('display_order', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='dj4xol.ResearchCategory')),
            ],
            options={
                'ordering': ['category__display_order', 'level', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fleet',
            name='defense_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fleet',
            name='offense_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='player',
            name='starting_labs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='starting_labs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='star',
            name='labs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='order_type',
            field=models.CharField(choices=[('TERRAFORM_GRAVITY', 'Terraform Gravity (1%)'), ('TERRAFORM_TEMPERATURE', 'Terraform Temperature (1%)'), ('TERRAFORM_RADIATION', 'Terraform Radiation (1%)'), ('BUILD_FLEET', 'Build Fleet'), ('BUILD_MINE', 'Build Mine'), ('BUILD_FACTORY', 'Build Factory'), ('BUILD_LAB', 'Build Lab'), ('BUILD_DEFENSE', 'Build Defense'), ('BUILD_SHIPYARD', 'Build Shipyard')], max_length=24),
        ),
        migrations.AlterField(
            model_name='star',
            name='ironium_inventory',
            field=models.IntegerField(default=dj4xol.models.random_surface_ironium_init),
        ),
        migrations.AddField(
            model_name='playerresearch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_progress', to='dj4xol.ResearchCategory'),
        ),
        migrations.AddField(
            model_name='playerresearch',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_progress', to='dj4xol.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='technology',
            unique_together=set([('category', 'level', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerresearch',
            unique_together=set([('player', 'category')]),
        ),
    ]
