# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-23 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0043_auto_20260223_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerresearch',
            options={'ordering': ['category', 'player']},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['category', 'level', 'display_order', 'name']},
        ),
    ]
