# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-23 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0044_auto_20260223_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='max_safe_warp',
            field=models.IntegerField(default=2),
        ),
    ]
