# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-23 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def _rp_cost_for_level(level):
    if level <= 0:
        return 0
    if level == 1:
        return 50
    if level == 2:
        return 80
    prev = 80
    prev_prev = 50
    idx = 3
    while idx <= level:
        current = prev + prev_prev
        prev_prev = prev
        prev = current
        idx += 1
    return prev


def seed_default_and_category_requirements(apps, schema_editor):
    DefaultReq = apps.get_model('dj4xol', 'DefaultResearchLevelRequirement')
    CategoryReq = apps.get_model('dj4xol', 'ResearchLevelRequirement')
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')
    Technology = apps.get_model('dj4xol', 'Technology')

    max_tech_level = Technology.objects.aggregate(
        models.Max('level')
    ).get('level__max') or 0
    max_level = max(26, int(max_tech_level))

    existing_default_levels = set(
        DefaultReq.objects.values_list('level', flat=True)
    )
    missing_defaults = []
    for level in range(1, max_level + 1):
        if level in existing_default_levels:
            continue
        missing_defaults.append(DefaultReq(
            level=level,
            rp_cost=_rp_cost_for_level(level),
            ironium_cost=0,
            boranium_cost=0,
            germanium_cost=0,
        ))
    if missing_defaults:
        DefaultReq.objects.bulk_create(missing_defaults)

    defaults = list(DefaultReq.objects.all().order_by('level'))
    categories = list(ResearchCategory.objects.all())
    existing_pairs = set(
        CategoryReq.objects.values_list('category_id', 'level')
    )

    missing_category_rows = []
    for category in categories:
        for default in defaults:
            key = (category.id, default.level)
            if key in existing_pairs:
                continue
            missing_category_rows.append(CategoryReq(
                category_id=category.id,
                level=default.level,
                rp_cost=default.rp_cost,
                ironium_cost=default.ironium_cost,
                boranium_cost=default.boranium_cost,
                germanium_cost=default.germanium_cost,
            ))
    if missing_category_rows:
        CategoryReq.objects.bulk_create(missing_category_rows)


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0045_auto_20260223_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultResearchLevelRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('rp_cost', models.IntegerField(default=0)),
                ('ironium_cost', models.IntegerField(default=0)),
                ('boranium_cost', models.IntegerField(default=0)),
                ('germanium_cost', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='ResearchLevelRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('rp_cost', models.IntegerField(default=0)),
                ('ironium_cost', models.IntegerField(default=0)),
                ('boranium_cost', models.IntegerField(default=0)),
                ('germanium_cost', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_requirements', to='dj4xol.ResearchCategory')),
            ],
            options={
                'ordering': ['category', 'level'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='researchlevelrequirement',
            unique_together=set([('category', 'level')]),
        ),
        migrations.RunPython(seed_default_and_category_requirements, migrations.RunPython.noop),
    ]
