# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-23 22:10
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0046_add_research_level_requirements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='star',
            name='boranium_inventory',
            field=models.IntegerField(default=dj4xol.models.random_surface_boranium_init),
        ),
        migrations.AlterField(
            model_name='star',
            name='germanium_inventory',
            field=models.IntegerField(default=dj4xol.models.random_surface_germanium_init),
        ),
    ]
