# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-24 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0049_add_infrastructure_tech_type_and_construction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='convert_unused_buildpoints_to_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='singular_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='convert_unused_buildpoints_to_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='singular_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='starting_colonists',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='starting_labs',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='serverrace',
            name='starting_colonists',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='serverrace',
            name='starting_labs',
            field=models.IntegerField(default=1),
        ),
    ]
