# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-24 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0050_auto_20260224_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='spend_leftover_points_on_research',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='spend_leftover_points_on_research',
            field=models.BooleanField(default=False),
        ),
    ]
