# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-24 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0051_auto_20260224_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='thumbnail_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
