# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-28 23:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0066_fix_frigate_hull_thumbnail_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='HullDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('thumbnail_class', models.CharField(blank=True, default='scout', max_length=32)),
                ('offense_offset', models.FloatField(default=0.0)),
                ('defense_offset', models.FloatField(default=0.0)),
                ('ironium_cost', models.IntegerField(default=0)),
                ('boranium_cost', models.IntegerField(default=0)),
                ('germanium_cost', models.IntegerField(default=0)),
                ('grid_columns', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('grid_rows', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HullDesignSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('y', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('tech_type', models.CharField(choices=[('PROPULSION', 'Propulsion'), ('HULL', 'Hull'), ('ENERGY_WEAPON', 'Energy Weapon'), ('TORPEDO', 'Torpedo'), ('SHIELD', 'Shield'), ('ARMOUR', 'Armour'), ('INFRASTRUCTURE', 'Infrastructure'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('item_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('max_tech_level', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('display_order', models.IntegerField(default=0)),
                ('hull', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='dj4xol.HullDesign')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='hulldesignslot',
            unique_together=set([('hull', 'x', 'y')]),
        ),
    ]
