# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-01 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0067_auto_20260228_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hulldesignslot',
            name='tech_type',
            field=models.CharField(choices=[('ANY', 'Any'), ('MISC', 'Misc'), ('ANY_WEAPON', 'Any Weapon'), ('SHIELD_OR_ARMOUR', 'Shield or Armour'), ('PROPULSION', 'Propulsion'), ('HULL', 'Hull'), ('ENERGY_WEAPON', 'Energy Weapon'), ('TORPEDO', 'Torpedo'), ('SHIELD', 'Shield'), ('ARMOUR', 'Armour'), ('INFRASTRUCTURE', 'Infrastructure'), ('ELECTRICAL', 'Electrical'), ('MECHANICAL', 'Mechanical'), ('OTHER', 'Other')], default='OTHER', max_length=16),
        ),
    ]
