# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-01 00:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0068_auto_20260301_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='hulldesign',
            name='cargo_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hulldesign',
            name='cargo_hold_grid_height',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='hulldesign',
            name='cargo_hold_grid_width',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='hulldesign',
            name='fuel_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
