# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-01 00:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0069_auto_20260301_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hulldesign',
            name='cargo_hold_grid_height',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='hulldesign',
            name='cargo_hold_grid_width',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
