# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-01 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0071_auto_20260301_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_game_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='email_newsletter',
            field=models.BooleanField(default=True),
        ),
    ]
