# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-01 22:01
from __future__ import unicode_literals

from django.db import migrations


def unset_newsletter_opt_in(apps, schema_editor):
    Account = apps.get_model('dj4xol', 'Account')
    Account.objects.all().update(email_newsletter=False)


def noop_reverse(apps, schema_editor):
    # Intentionally non-reversible: previous per-user intent is unknown.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0072_auto_20260301_2029'),
    ]

    operations = [
        migrations.RunPython(unset_newsletter_opt_in, noop_reverse),
    ]
