# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-02 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0073_unset_existing_newsletter_opt_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serversettings',
            name='value',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
