# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-02 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0074_auto_20260302_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='has_bombs',
            field=models.CharField(blank=True, choices=[('CONVENTIONAL', 'Conventional'), ('SMART', 'Smart'), ('NOVA', 'Nova')], default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='has_fuel_factory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fleet',
            name='has_miners',
            field=models.CharField(blank=True, choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='fleet',
            name='has_wormhole_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('INTERCEPT', 'Intercept'), ('TRANSFER', 'Transfer'), ('COLONISE', 'Colonise'), ('BOMB', 'Bomb'), ('REMOTEMINE', 'Remote Mine'), ('MERGE', 'Merge'), ('SCUTTLE', 'Scuttle'), ('PATROL', 'Patrol')], max_length=16),
        ),
    ]
