# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-02 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0075_auto_20260302_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='tech_type',
            field=models.CharField(choices=[('PROPULSION', 'Propulsion'), ('HULL', 'Hull'), ('ENERGY_WEAPON', 'Energy Weapon'), ('TORPEDO', 'Torpedo'), ('SHIELD', 'Shield'), ('ARMOUR', 'Armour'), ('INFRASTRUCTURE', 'Infrastructure'), ('MECHANICAL', 'Mechanical'), ('BOMB', 'Bomb'), ('OTHER', 'Other')], default='OTHER', max_length=16),
        ),
    ]
