# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-02 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0081_sync_tech_tree_wormhole_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('INTERCEPT', 'Intercept'), ('TRANSFER', 'Transfer'), ('COLONISE', 'Colonise'), ('BOMB', 'Bomb'), ('REMOTEMINE', 'Remote Mine'), ('MERGE', 'Merge'), ('SCUTTLE', 'Scuttle'), ('PATROL', 'Patrol')], default='MOVE', max_length=10),
        ),
    ]
