# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-02 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0083_sync_tech_tree_advanced_wormhole'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='wormhole_fuel_per_ly',
            field=models.FloatField(default=5.0),
        ),
    ]
