# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-02 17:47
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0086_sync_tech_tree_wormhole_mk3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('id', models.UUIDField(default=dj4xol.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(editable=False, max_length=12, unique=True)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('anomaly_type', models.CharField(blank=True, default='ANOMALY', max_length=24)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalys', to='dj4xol.Game')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='target_kind',
            field=models.CharField(blank=True, choices=[('OBJECT', 'Object'), ('SPACE', 'Space')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='target_short_id',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(choices=[('star', 'Star'), ('fleet', 'Fleet'), ('salvage', 'Salvage'), ('anomaly', 'Anomaly')], max_length=10),
        ),
    ]
