# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-02 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0088_backfill_fleetorder_target_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='anomalies_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anomaly',
            name='anomaly_type',
            field=models.CharField(blank=True, choices=[('NEBULA', 'Nebula'), ('COMET', 'Comet'), ('RIFT', 'Rift'), ('ANOMALY', 'Anomaly')], default='ANOMALY', max_length=24),
        ),
    ]
