# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 11:10
from __future__ import unicode_literals

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


def backfill_anomaly_heading_and_stability(apps, schema_editor):
    Anomaly = apps.get_model('dj4xol', 'Anomaly')
    for anomaly in Anomaly.objects.all():
        seed = anomaly.short_id or str(anomaly.id)
        anomaly.heading = float(sum(ord(ch) for ch in seed) % 360)
        if anomaly.stability is None or anomaly.stability < 0 or anomaly.stability > 100:
            anomaly.stability = 100
        anomaly.save(update_fields=['heading', 'stability'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0089_auto_20260302_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='heading',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='stability',
            field=models.IntegerField(default=100, validators=[MinValueValidator(0), MaxValueValidator(100)]),
        ),
        migrations.RunPython(backfill_anomaly_heading_and_stability, noop_reverse),
    ]
