# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 12:30
from __future__ import unicode_literals

from django.core import validators
from django.db import migrations, models
import dj4xol.models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0090_anomaly_heading_stability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='stability',
            field=models.IntegerField(default=dj4xol.models.random_anomaly_stability_init, validators=[validators.MinValueValidator(0), validators.MaxValueValidator(100)]),
        ),
    ]
