# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0091_anomaly_stability_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='anomaly_type',
            field=models.CharField(blank=True, choices=[('NEBULA', 'Nebula'), ('COMET', 'Comet'), ('RIFT', 'Rift'), ('BLACK_HOLE', 'Black Hole'), ('ANOMALY', 'Anomaly')], default='ANOMALY', max_length=24),
        ),
    ]
