# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0092_anomaly_black_hole_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='anomaly_type',
            field=models.CharField(blank=True, choices=[('NEBULA', 'Nebula'), ('COMET', 'Comet'), ('RIFT', 'Rift'), ('BLACK_HOLE', 'Black Hole'), ('WORMHOLE', 'Wormhole'), ('ANOMALY', 'Anomaly')], default='ANOMALY', max_length=24),
        ),
        migrations.AddField(
            model_name='anomaly',
            name='wormhole_pair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wormhole_pair_reverse', to='dj4xol.Anomaly'),
        ),
    ]
