# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0093_wormhole_anomaly_pairing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='tech_type',
            field=models.CharField(choices=[('PROPULSION', 'Propulsion'), ('HULL', 'Hull'), ('ENERGY_WEAPON', 'Energy Weapon'), ('TORPEDO', 'Torpedo'), ('SHIELD', 'Shield'), ('ARMOUR', 'Armour'), ('SCANNER', 'Scanner'), ('INFRASTRUCTURE', 'Infrastructure'), ('MECHANICAL', 'Mechanical'), ('BOMB', 'Bomb'), ('OTHER', 'Other')], default='OTHER', max_length=16),
        ),
    ]
