# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 19:41
from __future__ import unicode_literals

from django.db import migrations, models


def backfill_fleet_scanner_ranges(apps, schema_editor):
    Fleet = apps.get_model('dj4xol', 'Fleet')
    Fleet.objects.all().update(
        basic_scanner_range=20,
        advanced_scanner_range=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0094_add_scanner_tech_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='basic_scanner_range',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fleet',
            name='advanced_scanner_range',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_fleet_scanner_ranges, migrations.RunPython.noop),
    ]
