# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 19:42
from __future__ import unicode_literals

import os
import uuid

from django.db import migrations


def _load_defaults_rows():
    import yaml

    fixtures_path = os.path.join(
        os.path.dirname(os.path.dirname(__file__)),
        'fixtures',
        'defaults.yaml',
    )
    with open(fixtures_path, 'r') as handle:
        data = yaml.safe_load(handle) or []
    return data


def sync_tech_tree_scanners(apps, schema_editor):
    # Superseded by later canonical defaults sync migrations.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0095_add_fleet_scanner_ranges'),
    ]

    operations = [
        migrations.RunPython(sync_tech_tree_scanners, migrations.RunPython.noop),
    ]
