# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 22:15
from __future__ import unicode_literals

from django.db import migrations, models


def enable_no_scanners_for_existing_games(apps, schema_editor):
    Game = apps.get_model('dj4xol', 'Game')
    Game.objects.all().update(no_scanners=True)


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0096_sync_tech_tree_scanners'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='no_scanners',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(enable_no_scanners_for_existing_games, migrations.RunPython.noop),
    ]
