# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-03 23:41
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0097_add_game_no_scanners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='heading',
            field=models.FloatField(default=dj4xol.models.random_heading_init),
        ),
    ]
