# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-04 00:10
from __future__ import unicode_literals

from django.db import migrations, models


def backfill_wormhole_destruction_chance(apps, schema_editor):
    Fleet = apps.get_model('dj4xol', 'Fleet')
    for fleet in Fleet.objects.all():
        try:
            fuel_eff = float(getattr(fleet, 'fuel_efficiency', 1.0) or 1.0)
        except (TypeError, ValueError):
            fuel_eff = 1.0
        chance = 1.0 - fuel_eff
        if chance < 0.0:
            chance = 0.0
        if chance > 1.0:
            chance = 1.0
        fleet.wormhole_destruction_chance = chance
        fleet.save(update_fields=['wormhole_destruction_chance'])


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0098_auto_20260303_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleet',
            name='wormhole_destruction_chance',
            field=models.FloatField(default=0.1),
        ),
        migrations.RunPython(
            backfill_wormhole_destruction_chance,
            migrations.RunPython.noop,
        ),
    ]
