# -*- coding: utf-8 -*-
# Generated by Codex on 2026-03-04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0102_category_mineral_requirements_l10_l16'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerresearch',
            name='ironium_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerresearch',
            name='boranium_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerresearch',
            name='germanium_paid',
            field=models.IntegerField(default=0),
        ),
    ]
