# -*- coding: utf-8 -*-
# Generated by Codex on 2026-03-04
from __future__ import unicode_literals

from django.db import migrations, models


def backfill_rollups_per_day(apps, schema_editor):
    Account = apps.get_model('dj4xol', 'Account')
    for account in Account.objects.all():
        if not account.email_game_updates:
            account.email_game_rollups_per_day = 0
        elif not account.email_game_rollups_per_day:
            account.email_game_rollups_per_day = 1
        account.save(update_fields=['email_game_rollups_per_day'])


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0103_add_player_research_mineral_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_game_rollups_per_day',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='EmailRollupLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_count', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='email_rollups', to='dj4xol.Account')),
                ('game', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='email_rollups', to='dj4xol.Game')),
                ('player', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='email_rollups', to='dj4xol.Player')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.RunPython(backfill_rollups_per_day, migrations.RunPython.noop),
    ]
