# -*- coding: utf-8 -*-
# Generated by Codex on 2026-03-04
from __future__ import unicode_literals

import uuid

from django.db import migrations, models


def backfill_unsubscribe_keys(apps, schema_editor):
    Account = apps.get_model('dj4xol', 'Account')
    for account in Account.objects.filter(email_unsubscribe_key=''):
        account.email_unsubscribe_key = uuid.uuid4().hex
        account.save(update_fields=['email_unsubscribe_key'])


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0104_add_email_rollups'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_unsubscribe_key',
            field=models.CharField(default='', max_length=64, blank=True),
        ),
        migrations.RunPython(backfill_unsubscribe_keys, migrations.RunPython.noop),
    ]
