# -*- coding: utf-8 -*-
# Generated by Codex
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0105_add_email_unsubscribe_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchLevelPrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('min_level', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_prerequisites', to='dj4xol.ResearchCategory')),
                ('requires_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_levels', to='dj4xol.ResearchCategory')),
            ],
            options={
                'ordering': ['category', 'level', 'requires_category'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='researchlevelprerequisite',
            unique_together=set([('category', 'level', 'requires_category')]),
        ),
    ]

