# -*- coding: utf-8 -*-
# Generated by Codex
from __future__ import unicode_literals

from django.db import migrations


def seed_research_level_prerequisites(apps, schema_editor):
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')
    ResearchLevelPrerequisite = apps.get_model('dj4xol', 'ResearchLevelPrerequisite')

    def category(code):
        return ResearchCategory.objects.filter(code=code).first()

    def upsert(cat, level, req_cat, min_level):
        if not cat or not req_cat:
            return
        ResearchLevelPrerequisite.objects.update_or_create(
            category=cat,
            level=level,
            requires_category=req_cat,
            defaults={'min_level': min_level},
        )

    energy = category('ENERGY')
    electronics = category('ELECTRONICS')
    materials = category('MATERIALS')
    metaphysics = category('METAPHYSICS')
    construction = category('CONSTRUCTION')

    # Late-game gates: require mid and late progress from other categories.
    upsert(metaphysics, 17, electronics, 12)
    upsert(metaphysics, 17, energy, 14)

    upsert(construction, 17, materials, 12)
    upsert(construction, 17, metaphysics, 13)

    # End-game gate: require high Materials/Energy plus mid Electronics.
    upsert(metaphysics, 19, materials, 16)
    upsert(metaphysics, 19, energy, 16)
    upsert(metaphysics, 19, electronics, 12)

    # Early/mid-game gates to introduce prerequisites without heavy restriction.
    upsert(electronics, 8, energy, 5)
    upsert(materials, 8, construction, 6)
    upsert(energy, 12, materials, 9)
    upsert(construction, 12, materials, 10)
    upsert(construction, 4, materials, 3)


def unseed_research_level_prerequisites(apps, schema_editor):
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')
    ResearchLevelPrerequisite = apps.get_model('dj4xol', 'ResearchLevelPrerequisite')

    def category(code):
        return ResearchCategory.objects.filter(code=code).first()

    def delete(cat, level):
        if not cat:
            return
        ResearchLevelPrerequisite.objects.filter(category=cat, level=level).delete()

    metaphysics = category('METAPHYSICS')
    construction = category('CONSTRUCTION')
    electronics = category('ELECTRONICS')
    materials = category('MATERIALS')
    energy = category('ENERGY')

    delete(metaphysics, 17)
    delete(metaphysics, 19)
    delete(construction, 17)
    delete(electronics, 8)
    delete(materials, 8)
    delete(energy, 12)
    delete(construction, 12)
    delete(construction, 4)


def update_trans_spatial_defense_matrix_level(apps, schema_editor):
    Technology = apps.get_model('dj4xol', 'Technology')
    Technology.objects.filter(short_id='tech00000406').update(level=17)


def revert_trans_spatial_defense_matrix_level(apps, schema_editor):
    Technology = apps.get_model('dj4xol', 'Technology')
    Technology.objects.filter(short_id='tech00000406').update(level=16)


def update_technology_rebalance(apps, schema_editor):
    Technology = apps.get_model('dj4xol', 'Technology')
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')

    categories = {
        cat.code: cat
        for cat in ResearchCategory.objects.filter(
            code__in=[
                'ENERGY',
                'ELECTRONICS',
                'MATERIALS',
                'METAPHYSICS',
                'CONSTRUCTION',
            ]
        )
    }

    updates = [
        ('tech00000102', 'ELECTRONICS'),  # Adaptive Navigation Computers
        ('tech00000104', 'ENERGY'),       # Phase-Coupled Warp Frames
        ('tech00000107', 'ENERGY'),       # Inertial Shear Dampers
        ('tech00000303', 'MATERIALS'),    # Deflector Shield
        ('tech00000308', 'MATERIALS'),    # Phased Shield Array
        ('tech00000702', 'ELECTRONICS'),  # Scanner Array III
        ('tech00000704', 'ELECTRONICS'),  # Scanner Array V
        ('tech00000723', 'ELECTRONICS'),  # Colony Scanner Array IV
        ('tech00000726', 'ELECTRONICS'),  # Colony Scanner Array VII
        ('tech00000604', 'ELECTRONICS'),  # Smart Bombs
    ]
    for short_id, code in updates:
        category = categories.get(code)
        if category:
            Technology.objects.filter(short_id=short_id).update(category=category)

    Technology.objects.filter(short_id='tech00000309').update(
        tech_type='ELECTRICAL',
        params_json='{\"defense_level\": 1.10, \"offense_level\": 1.70}',
    )
    Technology.objects.filter(short_id='tech00000212').update(
        tech_type='ELECTRICAL',
    )

    terraforming = [
        {
            'short_id': 'tech00000407',
            'category': 'CONSTRUCTION',
            'level': 7,
            'name': 'Terraforming Control I',
            'description': 'Early terraforming control matrices enable limited planetary adjustment.',
            'tech_type': 'INFRASTRUCTURE',
            'params_json': '{"terraforming_rate": 0.01, "production_cost_overrides": {"TERRAFORM_GRAVITY": {"bp": 100, "ironium": 750, "boranium": 150, "germanium": 100, "colonists": 0}, "TERRAFORM_TEMPERATURE": {"bp": 100, "ironium": 200, "boranium": 660, "germanium": 140, "colonists": 0}, "TERRAFORM_RADIATION": {"bp": 100, "ironium": 50, "boranium": 475, "germanium": 475, "colonists": 0}}}',
            'display_order': 206,
            'enabled': True,
        },
        {
            'short_id': 'tech00000408',
            'category': 'MATERIALS',
            'level': 10,
            'name': 'Terraforming Control II',
            'description': 'Improved terraforming relays double adjustment rates and reduce per-point costs.',
            'tech_type': 'INFRASTRUCTURE',
            'params_json': '{"terraforming_rate": 0.02, "production_cost_overrides": {"TERRAFORM_GRAVITY": {"bp": 180, "ironium": 1350, "boranium": 270, "germanium": 180, "colonists": 0}, "TERRAFORM_TEMPERATURE": {"bp": 180, "ironium": 360, "boranium": 1188, "germanium": 252, "colonists": 0}, "TERRAFORM_RADIATION": {"bp": 180, "ironium": 90, "boranium": 855, "germanium": 855, "colonists": 0}}}',
            'display_order': 207,
            'enabled': True,
        },
        {
            'short_id': 'tech00000409',
            'category': 'CONSTRUCTION',
            'level': 16,
            'name': 'Terraforming Control III',
            'description': 'Advanced atmospheric and geological feedback loops enable faster terraforming.',
            'tech_type': 'INFRASTRUCTURE',
            'params_json': '{"terraforming_rate": 0.05, "production_cost_overrides": {"TERRAFORM_GRAVITY": {"bp": 350, "ironium": 3000, "boranium": 600, "germanium": 400, "colonists": 0}, "TERRAFORM_TEMPERATURE": {"bp": 350, "ironium": 800, "boranium": 2640, "germanium": 560, "colonists": 0}, "TERRAFORM_RADIATION": {"bp": 350, "ironium": 200, "boranium": 1900, "germanium": 1900, "colonists": 0}}}',
            'display_order': 208,
            'enabled': True,
        },
        {
            'short_id': 'tech00000410',
            'category': 'MATERIALS',
            'level': 22,
            'name': 'Terraforming Control IV',
            'description': 'Endgame terraforming arrays deliver rapid environmental stabilisation.',
            'tech_type': 'INFRASTRUCTURE',
            'params_json': '{"terraforming_rate": 0.10, "production_cost_overrides": {"TERRAFORM_GRAVITY": {"bp": 600, "ironium": 5250, "boranium": 1050, "germanium": 700, "colonists": 0}, "TERRAFORM_TEMPERATURE": {"bp": 600, "ironium": 1400, "boranium": 4620, "germanium": 980, "colonists": 0}, "TERRAFORM_RADIATION": {"bp": 600, "ironium": 350, "boranium": 3325, "germanium": 3325, "colonists": 0}}}',
            'display_order': 209,
            'enabled': True,
        },
    ]
    for entry in terraforming:
        category = categories.get(entry['category'])
        if not category:
            continue
        Technology.objects.update_or_create(
            short_id=entry['short_id'],
            defaults={
                'category': category,
                'level': entry['level'],
                'name': entry['name'],
                'description': entry['description'],
                'tech_type': entry['tech_type'],
                'params_json': entry['params_json'],
                'display_order': entry['display_order'],
                'enabled': entry['enabled'],
            },
        )


def revert_technology_rebalance(apps, schema_editor):
    Technology = apps.get_model('dj4xol', 'Technology')
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')

    categories = {
        cat.code: cat
        for cat in ResearchCategory.objects.filter(
            code__in=[
                'ENERGY',
                'ELECTRONICS',
                'MATERIALS',
                'METAPHYSICS',
                'CONSTRUCTION',
            ]
        )
    }

    updates = [
        ('tech00000102', 'METAPHYSICS'),
        ('tech00000104', 'METAPHYSICS'),
        ('tech00000107', 'METAPHYSICS'),
        ('tech00000303', 'METAPHYSICS'),
        ('tech00000308', 'METAPHYSICS'),
        ('tech00000702', 'METAPHYSICS'),
        ('tech00000704', 'METAPHYSICS'),
        ('tech00000723', 'METAPHYSICS'),
        ('tech00000726', 'METAPHYSICS'),
        ('tech00000604', 'METAPHYSICS'),
    ]
    for short_id, code in updates:
        category = categories.get(code)
        if category:
            Technology.objects.filter(short_id=short_id).update(category=category)

    Technology.objects.filter(short_id='tech00000309').update(
        tech_type='SHIELD',
        params_json='{\"defense_level\": 1.10, \"offense_level\": 0.20}',
    )
    Technology.objects.filter(short_id='tech00000212').update(
        tech_type='TORPEDO',
    )
    Technology.objects.filter(
        short_id__in=['tech00000407', 'tech00000408', 'tech00000409', 'tech00000410']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0106_add_research_level_prerequisite'),
    ]

    operations = [
        migrations.RunPython(
            update_trans_spatial_defense_matrix_level,
            revert_trans_spatial_defense_matrix_level,
        ),
        migrations.RunPython(
            update_technology_rebalance,
            revert_technology_rebalance,
        ),
        migrations.RunPython(
            seed_research_level_prerequisites,
            unseed_research_level_prerequisites,
        ),
    ]
