# -*- coding: utf-8 -*-
# Generated by Codex
from __future__ import unicode_literals

from django.db import migrations


def seed_research_level_prerequisites(apps, schema_editor):
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')
    ResearchLevelPrerequisite = apps.get_model('dj4xol', 'ResearchLevelPrerequisite')

    def category(code):
        return ResearchCategory.objects.filter(code=code).first()

    def upsert(cat, level, req_cat, min_level):
        if not cat or not req_cat:
            return
        ResearchLevelPrerequisite.objects.update_or_create(
            category=cat,
            level=level,
            requires_category=req_cat,
            defaults={'min_level': min_level},
        )

    energy = category('ENERGY')
    electronics = category('ELECTRONICS')
    materials = category('MATERIALS')
    metaphysics = category('METAPHYSICS')
    construction = category('CONSTRUCTION')

    # Late-game gates: require mid and late progress from other categories.
    upsert(metaphysics, 17, electronics, 12)
    upsert(metaphysics, 17, energy, 14)

    upsert(construction, 17, materials, 12)
    upsert(construction, 17, metaphysics, 13)

    # End-game gate: require high Materials/Energy plus mid Electronics.
    upsert(metaphysics, 19, materials, 16)
    upsert(metaphysics, 19, energy, 16)
    upsert(metaphysics, 19, electronics, 12)

    # Early/mid-game gates to introduce prerequisites without heavy restriction.
    upsert(electronics, 8, energy, 5)
    upsert(materials, 8, construction, 6)
    upsert(energy, 12, materials, 9)
    upsert(construction, 12, materials, 10)
    upsert(construction, 4, materials, 3)


def unseed_research_level_prerequisites(apps, schema_editor):
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')
    ResearchLevelPrerequisite = apps.get_model('dj4xol', 'ResearchLevelPrerequisite')

    def category(code):
        return ResearchCategory.objects.filter(code=code).first()

    def delete(cat, level):
        if not cat:
            return
        ResearchLevelPrerequisite.objects.filter(category=cat, level=level).delete()

    metaphysics = category('METAPHYSICS')
    construction = category('CONSTRUCTION')
    electronics = category('ELECTRONICS')
    materials = category('MATERIALS')
    energy = category('ENERGY')

    delete(metaphysics, 17)
    delete(metaphysics, 19)
    delete(construction, 17)
    delete(electronics, 8)
    delete(materials, 8)
    delete(energy, 12)
    delete(construction, 12)
    delete(construction, 4)


def update_trans_spatial_defense_matrix_level(apps, schema_editor):
    Technology = apps.get_model('dj4xol', 'Technology')
    Technology.objects.filter(short_id='tech00000406').update(level=17)


def revert_trans_spatial_defense_matrix_level(apps, schema_editor):
    Technology = apps.get_model('dj4xol', 'Technology')
    Technology.objects.filter(short_id='tech00000406').update(level=16)


def update_technology_rebalance(apps, schema_editor):
    Technology = apps.get_model('dj4xol', 'Technology')
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')

    categories = {
        cat.code: cat
        for cat in ResearchCategory.objects.filter(
            code__in=[
                'ENERGY',
                'ELECTRONICS',
                'MATERIALS',
                'METAPHYSICS',
                'CONSTRUCTION',
            ]
        )
    }

    updates = [
        ('tech00000102', 'ELECTRONICS'),  # Adaptive Navigation Computers
        ('tech00000104', 'ENERGY'),       # Phase-Coupled Warp Frames
        ('tech00000107', 'ENERGY'),       # Inertial Shear Dampers
        ('tech00000303', 'MATERIALS'),    # Deflector Shield
        ('tech00000308', 'MATERIALS'),    # Phased Shield Array
        ('tech00000702', 'ELECTRONICS'),  # Scanner Array III
        ('tech00000704', 'ELECTRONICS'),  # Scanner Array V
        ('tech00000723', 'ELECTRONICS'),  # Colony Scanner Array IV
        ('tech00000726', 'ELECTRONICS'),  # Colony Scanner Array VII
        ('tech00000604', 'ELECTRONICS'),  # Smart Bombs
    ]
    for short_id, code in updates:
        category = categories.get(code)
        if category:
            Technology.objects.filter(short_id=short_id).update(category=category)

    Technology.objects.filter(short_id='tech00000309').update(
        tech_type='ELECTRICAL',
        params_json='{\"defense_level\": 1.10, \"offense_level\": 1.70}',
    )
    Technology.objects.filter(short_id='tech00000212').update(
        tech_type='ELECTRICAL',
    )


def revert_technology_rebalance(apps, schema_editor):
    Technology = apps.get_model('dj4xol', 'Technology')
    ResearchCategory = apps.get_model('dj4xol', 'ResearchCategory')

    categories = {
        cat.code: cat
        for cat in ResearchCategory.objects.filter(
            code__in=[
                'ENERGY',
                'ELECTRONICS',
                'MATERIALS',
                'METAPHYSICS',
                'CONSTRUCTION',
            ]
        )
    }

    updates = [
        ('tech00000102', 'METAPHYSICS'),
        ('tech00000104', 'METAPHYSICS'),
        ('tech00000107', 'METAPHYSICS'),
        ('tech00000303', 'METAPHYSICS'),
        ('tech00000308', 'METAPHYSICS'),
        ('tech00000702', 'METAPHYSICS'),
        ('tech00000704', 'METAPHYSICS'),
        ('tech00000723', 'METAPHYSICS'),
        ('tech00000726', 'METAPHYSICS'),
        ('tech00000604', 'METAPHYSICS'),
    ]
    for short_id, code in updates:
        category = categories.get(code)
        if category:
            Technology.objects.filter(short_id=short_id).update(category=category)

    Technology.objects.filter(short_id='tech00000309').update(
        tech_type='SHIELD',
        params_json='{\"defense_level\": 1.10, \"offense_level\": 0.20}',
    )
    Technology.objects.filter(short_id='tech00000212').update(
        tech_type='TORPEDO',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0106_add_research_level_prerequisite'),
    ]

    operations = [
        migrations.RunPython(
            update_trans_spatial_defense_matrix_level,
            revert_trans_spatial_defense_matrix_level,
        ),
        migrations.RunPython(
            update_technology_rebalance,
            revert_technology_rebalance,
        ),
        migrations.RunPython(
            seed_research_level_prerequisites,
            unseed_research_level_prerequisites,
        ),
    ]
