# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-05 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0118_add_anomaly_spawn_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='research_cost_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='game',
            name='warp_speed_multiplier',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='player',
            name='defeated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='fixed_homeworld',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serverrace',
            name='fixed_homeworld',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fleet',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleets', to='dj4xol.Player'),
        ),
        migrations.AlterField(
            model_name='salvage',
            name='salvage_type',
            field=models.CharField(choices=[('SALVAGE', 'Salvage'), ('ASTEROID_FIELD', 'Asteroid Field'), ('ANCIENT_DEBRIS', 'Ancient Debris')], default='SALVAGE', max_length=24),
        ),
    ]
