# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-06 16:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


def seed_original_warpfactor(apps, schema_editor):
    FleetOrders = apps.get_model('dj4xol', 'FleetOrders')
    FleetOrders.objects.filter(original_warpfactor__isnull=True).update(
        original_warpfactor=models.F('warpfactor')
    )


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0124_add_fleet_transfer_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetorders',
            name='original_warpfactor',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(14)]),
        ),
        migrations.AddField(
            model_name='fleetorders',
            name='overmax_risk_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('INTERCEPT', 'Intercept'), ('TRANSFER', 'Transfer'), ('GIVE', 'Transfer Fleet'), ('COLONISE', 'Colonise'), ('BOMB', 'Bomb'), ('REMOTEMINE', 'Remote Mine'), ('MERGE', 'Merge'), ('SCUTTLE', 'Scuttle'), ('PATROL', 'Patrol')], default='MOVE', max_length=10),
        ),
        migrations.RunPython(seed_original_warpfactor, noop_reverse),
    ]
