# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-10 18:13
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0146_sync_race_type_tech_gates_from_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiplomaticContract',
            fields=[
                ('id', models.UUIDField(default=dj4xol.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(editable=False, max_length=12)),
                ('temperature', models.CharField(choices=[('PROPOSE', 'Propose'), ('REQUEST', 'Request'), ('DEMAND', 'Demand')], default='PROPOSE', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('FULFILLED', 'Fulfilled'), ('DECLINED', 'Declined'), ('COUNTERED', 'Countered'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='DRAFT', max_length=16)),
                ('sent_year', models.IntegerField(default=0)),
                ('accepted_year', models.IntegerField(blank=True, null=True)),
                ('handled_year', models.IntegerField(blank=True, null=True)),
                ('fulfilled_year', models.IntegerField(blank=True, null=True)),
                ('expires_year', models.IntegerField(default=0)),
                ('extend_on_accept_years', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_clause_type', models.CharField(choices=[('NOTHING', 'Nothing'), ('TECHNOLOGY', 'Technology'), ('STANCE', 'Stance'), ('RESOURCE_TO_WORLD', 'Resources To World'), ('RESOURCE_ON_GIVEN_FLEET', 'Resources On Given Fleet'), ('FLEET_BY_SHIP_COUNT', 'Fleet By Ship Count'), ('SPECIFIC_FLEET', 'Specific Fleet')], default='NOTHING', max_length=24)),
                ('request_stance', models.CharField(blank=True, choices=[('HOSTILE', 'Hostile'), ('COLD', 'Cold'), ('NEUTRAL', 'Neutral'), ('WARM', 'Warm'), ('ALLIED', 'Allied')], default='', max_length=8)),
                ('request_ship_count', models.IntegerField(default=0)),
                ('request_ironium', models.IntegerField(default=0)),
                ('request_boranium', models.IntegerField(default=0)),
                ('request_germanium', models.IntegerField(default=0)),
                ('request_resource_x', models.IntegerField(default=0)),
                ('request_resource_y', models.IntegerField(default=0)),
                ('request_resource_z', models.IntegerField(default=0)),
                ('request_colonists', models.IntegerField(default=0)),
                ('offer_clause_type', models.CharField(choices=[('NOTHING', 'Nothing'), ('TECHNOLOGY', 'Technology'), ('STANCE', 'Stance'), ('RESOURCE_TO_WORLD', 'Resources To World'), ('RESOURCE_ON_GIVEN_FLEET', 'Resources On Given Fleet'), ('FLEET_BY_SHIP_COUNT', 'Fleet By Ship Count'), ('SPECIFIC_FLEET', 'Specific Fleet')], default='NOTHING', max_length=24)),
                ('offer_stance', models.CharField(blank=True, choices=[('HOSTILE', 'Hostile'), ('COLD', 'Cold'), ('NEUTRAL', 'Neutral'), ('WARM', 'Warm'), ('ALLIED', 'Allied')], default='', max_length=8)),
                ('progress_ironium', models.IntegerField(default=0)),
                ('progress_boranium', models.IntegerField(default=0)),
                ('progress_germanium', models.IntegerField(default=0)),
                ('progress_resource_x', models.IntegerField(default=0)),
                ('progress_resource_y', models.IntegerField(default=0)),
                ('progress_resource_z', models.IntegerField(default=0)),
                ('progress_colonists', models.IntegerField(default=0)),
                ('progress_ship_count', models.IntegerField(default=0)),
                ('countered_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counter_offers', to='dj4xol.DiplomaticContract')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomaticcontracts', to='dj4xol.Game')),
                ('offer_fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dj4xol.Fleet')),
                ('offer_technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dj4xol.Technology')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_diplomatic_contracts', to='dj4xol.Player')),
                ('request_suggested_star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dj4xol.Star')),
                ('request_technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dj4xol.Technology')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_diplomatic_contracts', to='dj4xol.Player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerTechnologyGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_year', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technology_grants_given', to='dj4xol.Player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technology_grants', to='dj4xol.Player')),
                ('source_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technology_grants', to='dj4xol.DiplomaticContract')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_grants', to='dj4xol.Technology')),
            ],
            options={
                'ordering': ['technology__category', 'technology__level', 'technology__name'],
            },
        ),
        migrations.AlterField(
            model_name='serverracetype',
            name='warp_advantage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='playertechnologygrant',
            unique_together=set([('player', 'technology')]),
        ),
        migrations.AlterUniqueTogether(
            name='diplomaticcontract',
            unique_together=set([('game', 'short_id')]),
        ),
    ]
