# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-20 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0188_add_player_ancient_debris_discovery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='order_type',
            field=models.CharField(choices=[('TERRAFORM_GRAVITY', 'Terraform Gravity (1%)'), ('TERRAFORM_TEMPERATURE', 'Terraform Temperature (1%)'), ('TERRAFORM_RADIATION', 'Terraform Radiation (1%)'), ('BUILD_FLEET', 'Build Fleet'), ('BUILD_MINE', 'Build Mine'), ('BUILD_FACTORY', 'Build Factory'), ('BUILD_COLONISTS_1K', 'Produce 1k Colonists'), ('BUILD_COLONISTS_1M', 'Produce 1m Colonists'), ('BUILD_LAB', 'Build Lab'), ('BUILD_DEFENSE', 'Build Defense'), ('BUILD_SHIPYARD', 'Build Shipyard'), ('BUILD_ADMINISTRATION', 'Build Administration'), ('REMOVE_ADMINISTRATION', 'Remove Administration')], max_length=24),
        ),
    ]
