# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0193_add_electrical_or_mechanical_hull_slot_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_html_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
