# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-03-27 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0201_game_last_turn_execution_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleet',
            name='has_bombs',
            field=models.CharField(blank=True, choices=[('CONVENTIONAL', 'Conventional'), ('SMART', 'Smart'), ('NOVA', 'Nova'), ('SUPERNOVA', 'Supernova')], default=None, max_length=16, null=True),
        ),
    ]
