# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-04-06 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0226_sync_recent_tech_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetorders',
            name='order_type',
            field=models.CharField(choices=[('MOVE', 'Move'), ('INTERCEPT', 'Intercept'), ('REFUEL', 'Refuel'), ('TRANSFER', 'Transfer'), ('GIVE', 'Transfer Fleet'), ('COLONISE', 'Colonise'), ('BOMB', 'Bomb'), ('REMOTEMINE', 'Remote Mine'), ('MERGE', 'Merge'), ('SCUTTLE', 'Scuttle'), ('GENESIS', 'Activate Genesis'), ('PATROL', 'Patrol')], default='MOVE', max_length=10),
        ),
    ]
