# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-04-29 16:03
from __future__ import unicode_literals

import dj4xol.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dj4xol', '0229_playerdiplomaticstance_auto_downgrade_on_hostile_actions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicromanagerObjectState',
            fields=[
                ('id', models.UUIDField(default=dj4xol.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('short_id', models.CharField(editable=False, max_length=12)),
                ('target_type', models.CharField(choices=[('star', 'Star'), ('fleet', 'Fleet')], max_length=10)),
                ('primary_role', models.CharField(blank=True, default='', max_length=40)),
                ('mission', models.CharField(blank=True, default='', max_length=40)),
                ('tags_json', models.TextField(blank=True, default='[]')),
                ('data_json', models.TextField(blank=True, default='{}')),
                ('updated_year', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micromanagerobjectstates', to='dj4xol.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='micromanager_object_states', to='dj4xol.Player')),
                ('target_fleet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micromanager_states', to='dj4xol.Fleet')),
                ('target_star', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='micromanager_states', to='dj4xol.Star')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='micromanagerobjectstate',
            unique_together=set([('game', 'short_id'), ('player', 'target_type', 'target_star'), ('player', 'target_type', 'target_fleet')]),
        ),
        migrations.AlterIndexTogether(
            name='micromanagerobjectstate',
            index_together=set([('player', 'target_type', 'mission'), ('player', 'target_type', 'primary_role')]),
        ),
    ]
