"""Catalog ship thumbnails into the `ship_thumbnail_catalog.py` module.

Usage:
    pyenv exec python -m dj4xol.catalog_ship_thumbs
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
THUMBS_ROOT = PROJECT_ROOT / "dj4xol" / "static" / "dj4xol" / "images" / "thumbs" / "ship"
OUTPUT_MODULE = PROJECT_ROOT / "dj4xol" / "ship_thumbnail_catalog.py"


def build_catalog():
    by_class = defaultdict(list)
    for png in sorted(THUMBS_ROOT.rglob("*.png")):
        rel = png.relative_to(PROJECT_ROOT / "dj4xol" / "static").as_posix()
        by_class[png.parent.name].append(rel)
    return dict(sorted(by_class.items(), key=lambda item: item[0]))


def render_module(catalog):
    all_paths = []
    lines = [
        '"""Autogenerated ship thumbnail catalog. Do not edit by hand."""',
        "",
        "SHIP_THUMBNAILS_BY_CLASS = {",
    ]
    for ship_class, paths in catalog.items():
        lines.append(f'    "{ship_class}": [')
        for path in paths:
            lines.append(f'        "{path}",')
            all_paths.append(path)
        lines.append("    ],")
    lines.append("}")
    lines.append("")
    lines.append("ALL_SHIP_THUMBNAILS = [")
    for path in all_paths:
        lines.append(f'    "{path}",')
    lines.append("]")
    lines.append("")
    lines.append("SHIP_THUMBNAIL_COUNT = len(ALL_SHIP_THUMBNAILS)")
    lines.append("")
    return "\n".join(lines)


def main():
    catalog = build_catalog()
    if not catalog:
        raise SystemExit(f"No thumbnails found under {THUMBS_ROOT}")
    OUTPUT_MODULE.write_text(render_module(catalog), encoding="utf-8")
    total = sum(len(v) for v in catalog.values())
    print(f"Wrote {OUTPUT_MODULE} with {total} thumbnails across {len(catalog)} classes.")


if __name__ == "__main__":
    main()
