"""Catalog star thumbnails into the `star_thumbnail_catalog.py` module.

Usage:
    pyenv exec python -m dj4xol.catalog_star_thumbs
"""

from __future__ import annotations

from pathlib import Path

from .thumbnail_variants import ensure_blur_variants, is_blur_variant_path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
THUMBS_ROOT = PROJECT_ROOT / "dj4xol" / "static" / "dj4xol" / "images" / "thumbs" / "star"
OUTPUT_MODULE = PROJECT_ROOT / "dj4xol" / "star_thumbnail_catalog.py"


def build_catalog():
    paths = []
    for png in sorted(THUMBS_ROOT.rglob("*.png")):
        if is_blur_variant_path(png.name):
            continue
        rel = png.relative_to(PROJECT_ROOT / "dj4xol" / "static").as_posix()
        paths.append(rel)
    return paths


def render_module(paths):
    lines = [
        '"""Autogenerated star thumbnail catalog. Do not edit by hand."""',
        "",
        "ALL_STAR_THUMBNAILS = [",
    ]
    for path in paths:
        lines.append(f'    "{path}",')
    lines.append("]")
    lines.append("")
    lines.append("STAR_THUMBNAIL_COUNT = len(ALL_STAR_THUMBNAILS)")
    lines.append("")
    return "\n".join(lines)


def main():
    ensure_blur_variants(THUMBS_ROOT)
    paths = build_catalog()
    if not paths:
        raise SystemExit(f"No thumbnails found under {THUMBS_ROOT}")
    OUTPUT_MODULE.write_text(render_module(paths), encoding="utf-8")
    print(f"Wrote {OUTPUT_MODULE} with {len(paths)} thumbnails.")


if __name__ == "__main__":
    main()
