"""Catalog anomaly thumbnails into the `anomaly_thumbnail_catalog.py` module.

Usage:
    pyenv exec python -m dj4xol.catalog_anomaly_thumbs
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from .thumbnail_variants import ensure_blur_variants, is_blur_variant_path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
THUMBS_ROOT = PROJECT_ROOT / "dj4xol" / "static" / "dj4xol" / "images" / "thumbs" / "anomaly"
OUTPUT_MODULE = PROJECT_ROOT / "dj4xol" / "anomaly_thumbnail_catalog.py"


def build_catalog():
    by_type = defaultdict(list)
    for png in sorted(THUMBS_ROOT.rglob("*.png")):
        if is_blur_variant_path(png.name):
            continue
        rel = png.relative_to(PROJECT_ROOT / "dj4xol" / "static").as_posix()
        by_type[png.parent.name].append(rel)
    return dict(sorted(by_type.items(), key=lambda item: item[0]))


def render_module(catalog):
    all_paths = []
    lines = [
        '"""Autogenerated anomaly thumbnail catalog. Do not edit by hand."""',
        "",
        "ANOMALY_THUMBNAILS_BY_TYPE = {",
    ]
    for anomaly_type, paths in catalog.items():
        lines.append(f'    "{anomaly_type}": [')
        for path in paths:
            lines.append(f'        "{path}",')
            all_paths.append(path)
        lines.append("    ],")
    lines.append("}")
    lines.append("")
    lines.append("ALL_ANOMALY_THUMBNAILS = [")
    for path in all_paths:
        lines.append(f'    "{path}",')
    lines.append("]")
    lines.append("")
    lines.append("ANOMALY_THUMBNAIL_COUNT = len(ALL_ANOMALY_THUMBNAILS)")
    lines.append("")
    return "\n".join(lines)


def main():
    ensure_blur_variants(THUMBS_ROOT)
    catalog = build_catalog()
    if not catalog:
        raise SystemExit(f"No thumbnails found under {THUMBS_ROOT}")
    OUTPUT_MODULE.write_text(render_module(catalog), encoding="utf-8")
    total = sum(len(v) for v in catalog.values())
    print(f"Wrote {OUTPUT_MODULE} with {total} thumbnails across {len(catalog)} types.")


if __name__ == "__main__":
    main()
